### ISSUE TITLE
Creating build system

### ISSUE THREAD

**Issue by miladsade96** [EverLookNeverSee/numermp#4]
We will use python package manager for distributing and releasing this project, to do so, we need to create and configure **setup.py** file. Since this project isn't a pure python project, we need to consider options below:

- fortran source files contains openmp library. thus, we need to use **--f90flags="-fopenmp"** with **f2py**
- since we need to customize subroutines signature files(**.pyf**), we should use [f2py smart way](https://numpy.org/doc/stable/f2py/getting-started.html#the-smart-way)

To do so, we need to use [numpy distutils](https://numpy.org/doc/stable/reference/distutils.html) inside **setup.py**.

**Comment by EverLookNeverSee** [comment]
@melissawm 
you can install temporary build of project using command below:
`pip install -i https://test.pypi.org/simple/ numermp-test`

**Comment by EverLookNeverSee** [comment]
I tried to test it , but i got this error:
![error](https://user-images.githubusercontent.com/57490926/86230348-37999a00-bba6-11ea-9de6-522ab164504b.png)
